### PR TITLE
Theia 1.32.0 and yarn upgrade

### PR DESCRIPTION
**Pull request by EstFoisy**
#### What it does
• Update Theia to version 1.32.0
• Performed a yarn upgrade, to update the various npm dependencies we use in this repository.

#### How to test
Build Blueprint and check if everything is still working.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Review by marcdumais-work — APPROVED** [review]
LGTM - `yarn audit` found zero vulnerabilities! I briefly tested on GitPod and Blueprint looks to work well. Thanks @EstFoisy!

**Comment by marcdumais-work** [comment]
There might be an issue with the MacOS build - it seems to auto-cancel itself. When I manually try to re-start it, I get:
image

**Comment by vince-fugnitto** [comment]
@marcdumais-work it seems like an issue with using deprecated runners. I'll update them similarly to what I did in the main repo:

image

**Review by vince-fugnitto — APPROVED** [review]
LGTM :+1: 

- [x] confirmed that the build, start, and packaging works
- [x] confirmed that `1.32.0` is being used
- [x] confirmed that `yarn audit` does not produce any vulnerabilities output 
- [x] we do not encounter 429 errors as often due to the sequential update

**Pull request merged**
