### PR TITLE
A few tweaks to the new "cleanup" Jenkins file

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

Looking at the [log of the first run](https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/master/1/consoleFull), I noticed that seemingly no `yarn--<random number>` or `theia-plugin-download<random identifier>` file were found or cleaned. It was confirmed in the Gitlab ticket that these two types of files are still present on the server.

In this PR, I adapt the pattern we use for those two file types.  I also handle the case of the "theia-plugin-download**" files differently, looking-for and deleting individual files that match the pattern rather than directories.

Finally I made misc little tweaks based in linter feedback.

#### How to test

I think we will need to merge the PR in order for it to run on Jenkins?

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by jfaltermeier** [comment]
The name pattern of the lighthouse files contains the dot: `C:\Users\GENIE~1.THE\AppData\Local\Temp\lighthouse.46275455`
I have adjusted the job to also build this branch: https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/cleanup/

Currently it seems that the adjusted pattern does not work yet:
```
C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>echo "Before tmp/yarn Cleanup:" 
"Before tmp/yarn Cleanup:"
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>FOR / %i in (yarn--.*) do echo "%i" 
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>FOR / %i in (yarn--.*) do @rmdir /s /q "%i" 
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>echo "After tmp/yarn Cleanup:" 
"After tmp/yarn Cleanup:"
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>FOR / %i in (yarn--.*) do echo "%i" 
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>echo "Before tmp/plugin-download Cleanup:" 
"Before tmp/plugin-download Cleanup:"
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>FOR / %i in (theia-plugin-download.*) do echo "%i" 
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>FOR / %i in (theia-plugin-download.*) do @rmdir /s /q "%i" 
[Pipeline] bat

C:\Users\genie.theia\jenkins_agent\workspace\ia_-_Cleanup_Build_Nodes_cleanup>echo "After tmp/plugin-download Cleanup:" 
"After tmp/plugin-download Cleanup:"
[Pipeline] bat
```

Maybe we should temporarily list all contents of `"%temp%` at the beginning of the job to get a better picture?

**Comment by marcdumais-work** [comment]
Hi @jfaltermeier ,

Here's the content of the temp folder:
https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/cleanup/9/consoleFull

I think I see the problem now: we clean folders, but yarn and plugin files are plain files.

**Comment by marcdumais-work** [comment]
I think this run got the `yarn--` folders:
https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/cleanup/20/console

Change:
image

**Review by jfaltermeier — APPROVED** [review]
Thanks, LGTM! 
We could remove the commented out logs from `cleanYarnCache`, but I am also fine with keeping them in case we want to check whether the yarn cache clean still works in the future

**Comment by marcdumais-work** [comment]
> Thanks, LGTM! We could remove the commented out logs from `cleanYarnCache`, but I am also fine with keeping them in case we want to check whether the yarn cache clean still works in the future

Thanks for the feedback! I think I will remove these commented-out entries - from all this cleanup, these yarn cache are the less likely to fail I think.

**Comment by marcdumais-work** [comment]
@jfaltermeier Please have another look if you want? I have made changes to avoid failing the pipeline if no "theia-download" file is found (Windows is weird). I have also made changes, letting the linter guide me. It seems to start to behave well, even if no cleanup is necessary because of a recent run: 

https://ci.eclipse.org/theia/job/Theia%20-%20Cleanup%20Build%20Nodes/job/cleanup/38/console

I will squash the commits

**Comment by jfaltermeier** [comment]
@marcdumais-work Thanks, looks good. I've verified that that the temp dir contents look good after the run and that we can execute the cleanup twice in a row without build failures.

**Comment by marcdumais-work** [comment]
@jfaltermeier Thanks for the review and suggestions. I will squash into one commit and merge. Will you add a scheduled job, that periodically runs this "cleanup" Jenkins file?

**Pull request merged**
