### PR TITLE
[CI] Replace decommissioned build.eclipse.org server in Jenkins config

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

We use `build.eclipse.org` in our JenkinsFile and elsewhere. Let's try updating it to the suggested replacement server and hope this does the trick.

We also used a non-standard server for notarization: updated too.

more about the server decommission: 
https://wiki.eclipse.org/IT_Infrastructure_Doc#Web_service
https://www.eclipse.org/lists/eclipse.org-committers/msg01318.html
https://blogs.eclipse.org/post/denis-roy/bye-bye-build-end-era
https://bugs.eclipse.org/bugs/show_bug.cgi?id=565644

Also update URL of MacOS notarization service, in the few places
where we use the service, as per the documented example:
https://wiki.eclipse.org/IT_Infrastructure_Doc#macOS_Notarization

Use fail-fast option of curl, since this permits to immediately
detect if there's an issue with the macOS signing service, the
first time it's used.

E.g.:

ssh -q genie.theia@projects-storage.eclipse.org curl -f -o '"signed-ffmpeg.node"' -F 'file=@"ffmpeg.node"' -F entitlements=@entitlements.plist https://cbi.eclipse.org/macos/codesign/sign
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 36314    0     0  100 36314      0   571k --:--:-- --:--:-- --:--:--  571k
curl: (22) The requested URL returned error: 403

Replace child_process.execFileSync() by process.spawnSync() for both signing
and notarizing, so we can see related logs in real-time.

#### How to test

For the signing and notarization, we can partially test through CI (Jenkins), but the final step for both signing and notarizing  is only taken when on the main branch, i.e.for merged PRs. 

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
I rebased the PR on latest master.

**Comment by marcdumais-work** [comment]
The mac signing now works. I fixed a couple of problems with the notarization... getting close to work, I think.

**Comment by marcdumais-work** [comment]
Jenkins CI has passed 2/3 last tries. I am not sure this PR fixes everything but it should help.

**Review by vince-fugnitto — APPROVED** [review]
I'm fine with the changes, the CI is currently passing :+1:

**Comment by marcdumais-work** [comment]
Rebased on latest master

**Comment by marcdumais-work** [comment]
I'll go ahead and merge this PR. I'll do a follow-up if needed.

**Pull request merged**
