### PR TITLE
Enable dev-container support

### PR DESCRIPTION
**Pull request by jfaltermeier**
#### What it does
Adds @theia/dev-container

Contributed on behalf of STMicroelectronics

#### How to test
Build and check if still working as expected

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by jonah-iden** [comment]
@jfaltermeier could you look into the container if the copy of the backend is correct? My first guess would be that the backend copy would somehow be incorrect for the packaged version

**Comment by jfaltermeier** [comment]
> @jfaltermeier could you look into the container if the copy of the backend is correct? My first guess would be that the backend copy would somehow be incorrect for the packaged version

@jonah-iden Yes, it looks like it, when it is working it looks like this:

```
$ docker exec -it gracious_greider /bin/bash
root@06ee2c9dee3f:/# cd root/
root@06ee2c9dee3f:~# ls -al
total 36
drwx------ 1 root root 4096 Apr  3 13:57 .
drwxr-xr-x 1 root root 4096 Apr  3 13:57 ..
-rw-r--r-- 1 root root  571 Apr 10  2021 .bashrc
drwxr-xr-x 3 root root 4096 Mar 27 00:04 .cache
drwx------ 4 root root 4096 Mar 27 00:03 .gnupg
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
drwxr-xr-x 7 root root 4096 Apr  3 13:57 .theia-ide
drwxr-xr-x 4 root root 4096 Apr  3 13:57 .theia-ide-electron-app-1.48.200-remote
-rw-r--r-- 1 root root  254 Mar 12 11:54 .wget-hsts
root@06ee2c9dee3f:~# cd .theia-ide-electron-app-1.48.200-remote/
root@06ee2c9dee3f:~/.theia-ide-electron-app-1.48.200-remote# ls
lib  node-v18.17.0-linux-x64  node-v18.17.0-linux-x64.tar.xz  package.json  theia-ide-electron-app-1.48.200-remote.tar
root@06ee2c9dee3f:~/.theia-ide-electron-app-1.48.200-remote# cd lib/
root@06ee2c9dee3f:~/.theia-ide-electron-app-1.48.200-remote/lib# ls
backend  build	frontend  webview
root@06ee2c9dee3f:~/.theia-ide-electron-app-1.48.200-remote/lib# cd backend
root@06ee2c9dee3f:~/.theia-ide-electron-app-1.48.200-remote/lib/backend# ls -al
total 6660
drwxr-xr-x 5 root root    4096 Apr  3 13:57 .
drwxr-xr-x 6 root root    4096 Apr  3 13:57 ..
-rw-rw-r-- 1 root root   22002 Apr  3 11:27 196.js
-rw-rw-r-- 1 root root    9742 Apr  3 11:27 233.js
-rw-rw-r-- 1 root root 2439100 Apr  3 11:27 242.js
-rw-rw-r-- 1 root root  763949 Apr  3 11:27 339.js
-rw-rw-r-- 1 root root  366340 Apr  3 11:27 366.js
-rw-rw-r-- 1 root root   98442 Apr  3 11:27 418.js
-rw-rw-r-- 1 root root 1395864 Apr  3 11:27 638.js
-rw-rw-r-- 1 root root   81194 Apr  3 11:27 698.js
-rw-rw-r-- 1 root root 1083551 Apr  3 11:27 794.js
-rw-rw-r-- 1 root root  430085 Apr  3 11:27 801.js
-rw-rw-r-- 1 root root   19219 Apr  3 11:27 867.js
-rw-rw-r-- 1 root root    2695 Apr  3 11:27 backend-init-theia.js
-rw-rw-r-- 1 root root     702 Apr  3 11:27 dev-container-server.js
-rw-rw-r-- 1 root root   10632 Apr  3 11:27 electron-main.js
-rw-rw-r-- 1 root root   10842 Apr  3 11:27 ipc-bootstrap.js
-rw-rw-r-- 1 root root   13616 Apr  3 11:27 main.js
drwxr-xr-x 2 root root    4096 Apr  3 13:57 native
drwxr-xr-x 2 root root    4096 Apr  3 13:57 native-webpack-plugin
-rw-rw-r-- 1 root root    3550 Apr  3 11:27 nsfw-watcher.js
-rw-rw-r-- 1 root root    4061 Apr  3 11:27 plugin-host.js
-rw-rw-r-- 1 root root    7234 Apr  3 11:27 plugin-vscode-init.js
drwxr-xr-x 2 root root    4096 Apr  3 13:57 worker
root@06ee2c9dee3f:~/.theia-ide-electron-app-1.48.200-remote/lib/backend# 
```

And in the packaged use case it looks like this:
```
$ docker exec -it cranky_lewin /bin/bash
root@e6e856b4f1f4:/# cd /root
root@e6e856b4f1f4:~# ls -al
total 32
drwx------ 1 root root 4096 Apr  3 13:53 .
drwxr-xr-x 1 root root 4096 Apr  3 13:53 ..
-rw-r--r-- 1 root root  571 Apr 10  2021 .bashrc
drwxr-xr-x 3 root root 4096 Mar 27 00:04 .cache
drwx------ 4 root root 4096 Mar 27 00:03 .gnupg
-rw-r--r-- 1 root root  161 Jul  9  2019 .profile
drwxr-xr-x 4 root root 4096 Apr  3 13:53 .theia-ide-electron-app-1.48.200-remote
-rw-r--r-- 1 root root  254 Mar 12 11:54 .wget-hsts
root@e6e856b4f1f4:~# cd .theia-ide-electron-app-1.48.200-remote/
root@e6e856b4f1f4:~/.theia-ide-electron-app-1.48.200-remote# ls -al
total 25484
drwxr-xr-x 4 root root     4096 Apr  3 13:53 .
drwx------ 1 root root     4096 Apr  3 13:53 ..
drwxr-xr-x 4 root root     4096 Apr  3 13:53 lib
drwxr-xr-x 6 pn   pn       4096 Jul 18  2023 node-v18.17.0-linux-x64
-rw-rw-r-- 1 pn   pn   23839664 Apr  3 13:53 node-v18.17.0-linux-x64.tar.xz
-rw-rw-r-- 1 root root     2881 Apr  3 11:30 package.json
-rw-rw-r-- 1 pn   pn    2231287 Apr  3 13:53 theia-ide-electron-app-1.48.200-remote.tar

root@e6e856b4f1f4:~/.theia-ide-electron-app-1.48.200-remote# cd lib/
root@e6e856b4f1f4:~/.theia-ide-electron-app-1.48.200-remote/lib# ls -al
total 16
drwxr-xr-x 4 root root 4096 Apr  3 13:53 .
drwxr-xr-x 4 root root 4096 Apr  3 13:53 ..
drwxr-xr-x 3 root root 4096 Apr  3 13:53 backend
drwxr-xr-x 3 root root 4096 Apr  3 13:53 build
root@e6e856b4f1f4:~/.theia-ide-electron-app-1.48.200-remote/lib# cd backend/
root@e6e856b4f1f4:~/.theia-ide-electron-app-1.48.200-remote/lib/backend# ls -al
total 12
drwxr-xr-x 3 root root 4096 Apr  3 13:53 .
drwxr-xr-x 4 root root 4096 Apr  3 13:53 ..
drwxr-xr-x 2 root root 4096 Apr  3 13:53 native

```

When I check the packaged application on disk, the `lib/backend` directory looks OK though:
```
$ pwd
/home/johannes/Git/theia-blueprint/applications/electron/dist/linux-unpacked/resources/app/lib/backend
$ ls -al
total 6684
drwxrwxr-x 5 johannes johannes    4096 Apr  3 13:30 .
drwxrwxr-x 6 johannes johannes    4096 Apr  3 13:30 ..
-rw-rw-r-- 1 johannes johannes   22002 Apr  3 13:30 196.js
-rw-rw-r-- 1 johannes johannes      51 Apr  3 13:30 196.js.LICENSE.txt
-rw-rw-r-- 1 johannes johannes    9742 Apr  3 13:30 233.js
-rw-rw-r-- 1 johannes johannes     799 Apr  3 13:30 233.js.LICENSE.txt
-rw-rw-r-- 1 johannes johannes 2439100 Apr  3 13:30 242.js
-rw-rw-r-- 1 johannes johannes    3206 Apr  3 13:30 242.js.LICENSE.txt
-rw-rw-r-- 1 johannes johannes  763949 Apr  3 13:30 339.js
-rw-rw-r-- 1 johannes johannes  366340 Apr  3 13:30 366.js
-rw-rw-r-- 1 johannes johannes   98442 Apr  3 13:30 418.js
-rw-rw-r-- 1 johannes johannes 1395864 Apr  3 13:30 638.js
-rw-rw-r-- 1 johannes johannes   81194 Apr  3 13:30 698.js
-rw-rw-r-- 1 johannes johannes 1083551 Apr  3 13:30 794.js
-rw-rw-r-- 1 johannes johannes    5071 Apr  3 13:30 794.js.LICENSE.txt
-rw-rw-r-- 1 johannes johannes  430085 Apr  3 13:30 801.js
-rw-rw-r-- 1 johannes johannes     151 Apr  3 13:30 801.js.LICENSE.txt
-rw-rw-r-- 1 johannes johannes   19219 Apr  3 13:30 867.js
-rw-rw-r-- 1 johannes johannes    2695 Apr  3 13:30 backend-init-theia.js
-rw-rw-r-- 1 johannes johannes     702 Apr  3 13:30 dev-container-server.js
-rw-rw-r-- 1 johannes johannes   10632 Apr  3 13:30 electron-main.js
-rw-rw-r-- 1 johannes johannes   10842 Apr  3 13:30 ipc-bootstrap.js
-rw-rw-r-- 1 johannes johannes   13616 Apr  3 13:30 main.js
drwxrwxr-x 2 johannes johannes    4096 Apr  3 13:30 native
drwxrwxr-x 2 johannes johannes    4096 Apr  3 13:30 native-webpack-plugin
-rw-rw-r-- 1 johannes johannes    3550 Apr  3 13:30 nsfw-watcher.js
-rw-rw-r-- 1 johannes johannes    4061 Apr  3 13:30 plugin-host.js
-rw-rw-r-- 1 johannes johannes    7234 Apr  3 13:30 plugin-vscode-init.js
drwxrwxr-x 2 johannes johannes    4096 Apr  3 13:30 worker

```

**Comment by msujew** [comment]
@jfaltermeier Probably related to https://github.com/eclipse-theia/theia/issues/13140. I can take a look at this in the coming days.

**Comment by jfaltermeier** [comment]
Thanks

**Comment by jfaltermeier** [comment]
Closing in favour of https://github.com/eclipse-theia/theia-blueprint/pull/359

**Pull request closed without merging**
