### PR TITLE
update to latest @theia: v1.14.0

### PR DESCRIPTION
**Pull request by marcdumais-work**
Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>

#### What it does

Updates Blueprint to use the latest Theia framework, v1.14.0

#### How to test

Build PR and check that it still builds and run, both "in-place" and packaged.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
I see this trace in the backend, a bit after startup:

```
root ERROR [hosted-plugin: 18104] Promise rejection not handled in one second: Error: Command with id 'extension.js-debug.clearAutoAttachVariables' is not registered. , reason: Error: Command with id 'extension.js-debug.clearAutoAttachVariables' is not registered.
root ERROR [hosted-plugin: 18104] With stack trace: Error: Command with id 'extension.js-debug.clearAutoAttachVariables' is not registered.
    at e.<anonymous> (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3522434)
    at file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3520389
    at Object.next (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3520494)
    at file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3519406
    at new Promise (<anonymous>)
    at r (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3519151)
    at e.$executeCommand (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3522305)
    at e.doInvokeHandler (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3466807)
    at e.invokeHandler (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3466540)
    at e.receiveRequest (file:///tmp/.mount_TheiaBB3FKfa/resources/app/lib/bundle.js:2:3465872)
root ERROR [hosted-plugin: 18104] Promise rejection not handled in one second: undefined , reason: undefined

```

**Comment by marcdumais-work** [comment]
`"ms-vscode.js-debug": "https://open-vsx.org/api/ms-vscode/js-debug/1.52.2/file/ms-vscode.js-debug-1.52.2.vsix",`

This is probably a bit too recent. I'll switch to an older version and see if it helps.

**Comment by marcdumais-work** [comment]
> We use 1.49.8 in the main example app - that version looks promising

I do not see the exception any more. I think we'll use this version.

**Review by vince-fugnitto — APPROVED** [review]
The changes look good, I confirm it builds and starts :+1:

**Pull request merged**
