### PR TITLE
Integrate License Check

### PR DESCRIPTION
**Pull request by jfaltermeier**
#### What it does

* adds scripts and workflow for license checks
* enable automatic review

Contributed on behalf of STMicroelectronics

#### How to test

Check workflow on this PR
Run script locally using `yarn license:check`

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by marcdumais-work** [comment]
> I've generated a PAT, however I don't have the admin rights to add secrets on the repository

Hi @jfaltermeier , a PAT is not necessary at first I think(*). But if you are a committer in a repo, you can set a secret using the GitHub API. I've been using an old version of this [docker appliance](https://github.com/benoitf/github-secrets-generator) to do so myself.

(*): for security reasons, GitHub will only allow a secret be used for PRs that originate from this repo, not forks, so the "auto-review" mode will in any case not always be available.

**Review by marcdumais-work — COMMENTED** [review]
The PR looks good so far. If you go ahead and add a PAT as a repository secret, you may want to enable `review` in the config (it's safe to do so anyway - the license check should proceed in non-review mode if the PAT is not set, giving a warning).

**Comment by jfaltermeier** [comment]
Thanks, I've added the PAT and it seems to be working: https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/?sort=created_date&state=opened&author_username=jfaltermeier&in=DESCRIPTION&search=ecd.theia&first_page_size=20
Now we have to wait for the reviews to conclude

**Comment by marcdumais-work** [comment]
FYI, IP Tickets for 3PPs like [@types/lodash.union/4.6.9](https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/13549) don't seem to be handled too well by the "license check bot" on EF Gitlab. I think such package's sources are hosted in a huge repo (DefinitelyTyped), along with thousands of other similar packages for other 3PPs. The bot seemingly can't figure-out how to get the sources archive corresponding to these individual components and so can't analyse them.

It's almost certain there is no IP issue with such a `@types` package, but since the bot falls short, manual intervention from the IP team is needed. For such cases, you could optionally use the exclusion feature of the nodejs wrapper, so they would be ignored in the final license check assessment (i.e. not fail the check).

**Comment by marcdumais-work** [comment]
> It's ok and probably cleaner to wait 

Another option, that I am taking [in one of my recent PR](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1052/commits/052889520b32befd8bf44d44bb0477ee5dd434a6), is to use the "exclusion" feature of the `dash-licenses wrapper`, to ignore some of the dependencies that fail the license check. This way the license check momentarily passes and will be useful to detect further components with unclear licenses, while the few outstanding dependencies are analysed by the IP team.



IMHO, one needs to reasonably believe that the components, so excluded from the license check, are of an appropriate license for the project, and are being or to be reviewed by the IP team.

**Pull request merged**
