### PR TITLE
update to @theia v1.18.0

### PR DESCRIPTION
**Pull request by marcdumais-work**
#### What it does

This updates Blueprint so it uses the latest version of the Theia framework: v1.18.0. 

#### How to test

Build Blueprint and quickly manually test that it still seems to work well. One area where regressions are likely is in the support for vscode extensions, since Theia v1.18.0 stepped the supported vscode extension API to [1.53.2](https://github.com/tsmaeder/theia/blob/fa7eef40cee894b336809fcf87c803de2d9ec970/packages/plugin-ext-vscode/src/common/plugin-vscode-types.ts#L17), the open-vsx client will now often pick more recent versions of extensions, which can uncover issues that were not present in older versions of an extension.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I've added a commit on top of the changes in order to update the supported vscode api version (from `1.53.2` to `1.50.0`):

_before_:



blueprint-before

_after_:

blueprint-after

**Comment by marcdumais-work** [comment]
Note: after offline discussion we decided to keep vscode extension API 1.53.2, but have an example how we could override the framework's default, if we need to do so in the future. Vince adapted his commit in consequence.

**Review by jfaltermeier — APPROVED** [review]
Looks good to me! 
Uncommenting the examnple in theia-electron-main.js works as well. Would it make sense to add a short section about this in the documentation at https://theia-ide.org/docs/blueprint_documentation/ ?

**Comment by marcdumais-work** [comment]
> Would it make sense to add a short section about this in the documentation at https://theia-ide.org/docs/blueprint_documentation/ ?

Yes, I think so. I think the important thing to document is that it's possible to tweak the version of the vscode extension API, used by Blueprint, using an environment variable (the same one used in the example). The commented-out example will potentially be useful to us, if ever we are in a situation where we want to be more conservative vs the framework, about the API version to use.

**Pull request merged**
