### PR TITLE
Improve error reporting on failed updates

### LINKED ISSUE #45: Improve error reporting on failed updates
At the moment the "Check for updates" action fails silently, e.g. if there is no connection or the URL is not available. It would be nice to show the user at least that the update has failed, ideally of course why.

### PR DESCRIPTION
**Pull request by jfaltermeier**
#### What it does
* show that an error has happened
* the error we receive has no nice description of what went wrong so
just notify about error for now
* closes #45

Contributed on behalf of STMicroelectronics

Signed-off-by: Johannes Faltermeier <jfaltermeier@eclipsesource.com>

#### How to test
Disconnect from the Internet and start an update (File -> Settings -> Check for Updates)
Error is reported as a message in bottom right corner

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by brianking** [comment]
Does this address #71 in any way?

**Comment by jfaltermeier** [comment]
Should be merged after https://github.com/eclipse-theia/theia-blueprint/pull/94 adressing #71 
I'll restart the CI

**Comment by marcdumais-work** [comment]
@jfaltermeier it's possible that rebasing the PR on master will help with CI. I recently added [a cleanup](https://github.com/eclipse-theia/theia-blueprint/commit/ad5a73c519d79d740e808296c1520962749ad167) for two "local storage" directories used for CI, that could sometimes become corrupted and prevent successful builds.

**Comment by jfaltermeier** [comment]
> @jfaltermeier it's possible that rebasing the PR on master will help with CI. I recently added [a cleanup](https://github.com/eclipse-theia/theia-blueprint/commit/ad5a73c519d79d740e808296c1520962749ad167) for two "local storage" directories used for CI, that could sometimes become corrupted and prevent successful builds.

Yes, thank you. Build is green now

**Review by JonasHelming — APPROVED** [review]

**Pull request merged**
