### PR TITLE
Split updater and product branding

### LINKED ISSUE #42: Split updater and product branding
It would be useful to split the updater feature (that is generic) and the blueprint product customizations.

We (EclipseSource) intend to contribute to this on behalf of ST Microelectronics.

### PR DESCRIPTION
**Pull request by JonasHelming**
fixed #42

Contributed on behalf of STMicroelectronics

Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>

#### What it does
Splits updater and product branding in two separate extensions

#### How to test
Check About dialog, getting started and update still works.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

### CODE REVIEW

**Comment by JonasHelming** [comment]
@jfaltermeier Could you do check this please?

**Review by jfaltermeier — CHANGES_REQUESTED** [review]
Looks good to me, thanks. 
What is missing is to update the README.md to reflect the changes to the Repository structure.

**Comment by JonasHelming** [comment]
Very good catch, updated!

**Review by jfaltermeier — APPROVED** [review]
Thanks, looks good. @thegecko can you please have a look as well and merge this?

**Comment by thegecko** [comment]
> Thanks, looks good. @thegecko can you please have a look as well and merge this?

Can one of you request access to this repo so I don't continue to be a blocker for your work?

**Comment by marcdumais-work** [comment]
> Can one of you request access to this repo so I don't continue to be a blocker for your work?

The way forward is through one or more nomination(s) for project committership. Rob, you've been involved more closely here, and may be able to judge if it's time yet. I have noticed @jfaltermeier and @lucas-koehler have numerous commits in this repo, which I think will gain in importance in 2021. @koegel has been quite present as well, helping organize the work.

**Comment by thegecko** [comment]
ack, @jfaltermeier  are you happy for me to nominate you?

**Comment by jfaltermeier** [comment]
> ack, @jfaltermeier are you happy for me to nominate you?

Yes, thank you

**Pull request merged**
