### PR TITLE
Remove Travis CI config file

### PR DESCRIPTION
**Pull request by Atharva321**
#### What it does

Fixes: #144, by removing the `travis.yaml` file.

#### How to test

N/A.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Atharva321 <atharvapatil19202@gmail.com>

### CODE REVIEW

**Review by vince-fugnitto — COMMENTED** [review]
@Atharva321 thank you for your first contribution to the project :+1: 

In order to accept your changes please be sure to sign the [eclipse contributor agreement (eca)](https://github.com/eclipse-theia/theia/blob/master/CONTRIBUTING.md#eclipse-contributor-agreement) with the same email as your authorship (it is the reason for the failed CI check).

**Comment by Atharva321** [comment]
ok doing

**Comment by Atharva321** [comment]
Done

**Comment by marcdumais-work** [comment]
> Done

Confirmed:
image

**Review by marcdumais-work — APPROVED** [review]
LGTM, thanks @Atharva321

**Pull request merged**
