### PR TITLE
Bump dependencies to v1.12.1, add new Theia extensions

### PR DESCRIPTION
**Pull request by DukeNgn**
#### What it does

+ The following commit bumps dependencies to `1.12.1`, following the release from Theia upstream repo.
+ `@theia/bulk-edit` is now explicit.
+ The commit also adds new Theia extensions:
	- `@theia/external-terminal`
	- `@theia/property-view`

#### How to test
+ The app should be built/packaged successfully.

#### Review checklist

- [x] as an author, I have thoroughly tested my changes and carefully followed [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#requesting-a-review)

#### Reminder for reviewers

- as a reviewer, I agree to behave in accordance with [the review guidelines](https://github.com/theia-ide/theia/blob/master/doc/pull-requests.md#reviewing)

Signed-off-by: Duc Nguyen <duc.a.nguyen@ericsson.com>

### CODE REVIEW

**Review by marcdumais-work — APPROVED** [review]
LGTM (CI still pending)

**Comment by marcdumais-work** [comment]
Thanks for the update @DukeNgn . Among other things, this will make your new [external terminal](https://github.com/eclipse-theia/theia/pull/9186) available in `Blueprint`!

**Comment by brianking** [comment]
When can we expect a 1.12.0 build?

**Comment by brianking** [comment]
I wonder if we should upgrade to v1.12.1 first before making a new build?
https://community.theia-ide.org/t/eclipse-theia-v1-12-1-patch-release/1588

**Comment by DukeNgn** [comment]
@brianking I updated the PR to bump dependencies to v1.12.1 instead so we can benefit from the recent patch release.

**Review by thegecko — APPROVED** [review]
LGTM

**Review by vince-fugnitto — APPROVED** [review]

**Comment by marcdumais-work** [comment]
@DukeNgn I suggest you rebase on this recent [PR](https://github.com/eclipse-theia/theia-blueprint/pull/64) by @thegecko , that will likely clear the failing CI

**Comment by DukeNgn** [comment]
@marcdumais-work Done! Waiting for CI check again 👍

**Comment by marcdumais-work** [comment]
All green now - merging. Thanks @DukeNgn!

**Pull request merged**
